apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcu-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: dcu-dp-ds
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: dcu-dp-ds
    spec:
      nodeSelector:
        dcu: "on"
      serviceAccountName: dcu-device-plugin
      hostPID: true
      hostNetwork: true
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - image: projecthami/dcu-vgpu-device-plugin:v1.0.5
        #command: ["/bin/bash","-c","source /opt/hygondriver/env.sh && sleep infinity"]
        command: [ "/root/k8s-device-plugin" ]
        name: dcu-dp-cntr
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HYGONPATH
          value: /opt/dtk
        - name: BASH_ENV
          value: ~/.bashrc
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            drop: [ "ALL" ]
            add: [ "SYS_ADMIN" ]
        volumeMounts:
        - name: dp
          mountPath: /var/lib/kubelet/device-plugins
        - name: sys
          mountPath: /sys
        - name: dev
          mountPath: /dev
        - name: vdev
          mountPath: /etc/vdev
        - name: hwpath
          mountPath: /usr/share/hwdata
        - name: hygonloc
          mountPath: /opt/hygondriver/
        - name: lib
          mountPath: /usr/local/vgpu
        - name: hyhal
          mountPath: /opt/hyhal
      volumes:
      - name: dp
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: sys
        hostPath:
          path: /sys
      - name: dev
        hostPath:
          path: /dev
      - name: vdev
        hostPath:
          path: /etc/vdev
          type: Directory
      - name: hwpath
        hostPath:
          path: /usr/share/hwdata
      - name: hygonloc
        hostPath:
          path: /opt/dtk
      - name: lib
        hostPath:
          path: /usr/local/vgpu
      - name: hyhal
        hostPath:
          path: /opt/hyhal
